config/routes.rb
Rails.application.routes.draw do
  get 'sections/new'

  root 'books#index'

  resources :books do
    get 'preview', on: :member
    resources :chapters do
      resources :sections
    end
  end

end

app/models/book.rb
class Book < ActiveRecord::Base
  has_many :chapters

  validates :title, presence: true
end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
  belongs_to :book
  has_many :sections

  validates :title, presence: true
end

app/models/section.rb
class Section < ActiveRecord::Base
  belongs_to :chapter

  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :fetch_book, only: [:show, :destroy, :edit, :update, :preview]

  def index
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to book_path(@book)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @book.update_attributes(book_params)
      redirect_to book_path(@book)
    else
      render :edit
    end
  end

  def show
  end

  def destroy
    @book.destroy
    redirect_to root_path, notice: "Book deleted successfully"
  end

  def preview
    @chapters = @book.chapters.includes(:sections)
  end

private
  def book_params
    params.require(:book).permit(:title, :description)
  end

  def fetch_book
    @book = Book.find(params[:id])
  end
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  before_action :fetch_book
  before_action :fetch_chapter, only: [:show, :destroy, :edit, :update]

  def new
    @chapter = @book.chapters.new
  end

  def create
    @chapter = @book.chapters.new(chapter_params)
    if @chapter.save
      redirect_to book_chapter_path(@book, @chapter)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @chapter.update_attributes(chapter_params)
      redirect_to book_chapter_path(@book, @chapter), notice: "Chapter updated successfully"
    else
      render :edit
    end
  end

  def show
  end

  def destroy
    @chapter.destroy
    redirect_to book_path(@book), notice: "Chapter deleted successfully"
  end

private
  def fetch_book
    @book = Book.find(params[:book_id])
  end

  def fetch_chapter
    @chapter = @book.chapters.find(params[:id])
  end

  def chapter_params
    params.require(:chapter).permit(:title, :notes)
  end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :fetch_chapter
  before_action :fetch_section, only: [:show, :edit, :update, :destroy]

  def new
    @section = @chapter.sections.new
  end

  def create
    @section = @chapter.sections.new(section_params)
    if @section.save
      redirect_to book_chapter_section_path(@book, @chapter, @section), notice: "Section created successfully"
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @section.update_attributes(section_params)
      redirect_to book_chapter_section_path(@book, @chapter, @section), notice: "Section updated successfully"
    else
      render :edit
    end
  end

  def destroy
    @section.destroy
    redirect_to book_chapter_path(@book, @chapter)
  end

private
  def fetch_chapter
    @book = Book.find(params[:book_id])
    @chapter = @book.chapters.find(params[:chapter_id])
  end

  def fetch_section
    @section = @chapter.sections.find(params[:id])
  end

  def section_params
    params.require(:section).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/books/_form.html.erb
<%= simple_form_for @book do |f| %>
  <%= f.input :title, placeholder: "Eg. how to play guitar" %>
  <%= f.input :description %>
  <%= f.submit "Add Book", class: "btn btn-primary btn-lg" %>
<% end %>

app/views/books/edit.html.erb
<h1>Edit <%= @book.title %></h1>
<%= render 'books/form' %>

app/views/books/index.html.erb
<%= link_to "Add a new Book", new_book_path, class: "pull-right btn btn-primary" %>
<h1>Pick a book to contribute</h1>
<% Book.all.each do |book| %>
  <div class="well">
    <%= link_to "Preview", preview_book_path(book), class: "btn btn-primary btn-sm pull-right" %>
    <h3><%= link_to book.title, book_path(book) %></h3>
    <p>
      <%= book.description %>
    </p>
  </div>
<% end %>

app/views/books/new.html.erb
<h1>Add new Book</h1>
<%= render 'books/form' %>

app/views/books/preview.html.erb
<h1><%= @book.title %></h1>
<% chapter_count = 1 %>
<% @chapters.each do |chapter| %>
  <h2><%= chapter_count %>. <%= chapter.title %></h2>
  <% section_count = 1 %>
  <% chapter.sections.each do |section| %>
    <h3><%= "#{chapter_count}.#{section_count}." %><%= section.title %></h3>
    <p>
      <%= section.content %>
    </p>
    <% section_count += 1 %>
  <% end %>
  <% chapter_count += 1 %>
<% end %>

app/views/books/show.html.erb
<%= link_to "Delete", book_path(@book), method: :delete, class: "btn btn-danger pull-right", data: {confirm: "Are you sure you want to delete the book?"} %>
<%= link_to "Edit", edit_book_path(@book), class: "btn btn-primary pull-right" %>
<%= link_to "Add Chapter", new_book_chapter_path(@book), class: "btn btn-success pull-right" %>

<h1><%= @book.title %></h1>
<p><%= @book.description %></p>

<table class="table table-striped table-hover">
  <% @book.chapters.each do |chapter| %>
  <tr>
    <td>
      <%= link_to chapter.title, book_chapter_path(@book, chapter) %>
    </td>
  </tr>
  <% end %>
</table>

app/views/chapters/_form.html.erb
<%= simple_form_for [@book, @chapter] do |f| %>
  <%= f.input :title %>
  <%= f.input :notes %>
  <%= f.submit "Add Chapter", class: "btn btn-primary btn-lg" %>
<% end %>

app/views/chapters/edit.html.erb
<h1>Edit chapter: <%= @chapter.title %></h1>
<%= render '/chapters/form' %>

app/views/chapters/new.html.erb
<h1>Add new chapter to <%= @book.title %></h1>
<%= render '/chapters/form' %>

app/views/chapters/show.html.erb
<%= link_to "Delete", book_chapter_path(@book, @chapter), method: :delete, class: "btn btn-danger pull-right", data: {confirm: "Are you sure you want to delete the chapter?"} %>
<%= link_to "Edit", edit_book_chapter_path(@book, @chapter), class: "btn btn-primary pull-right" %>
<%= link_to "Add section", new_book_chapter_section_path(@book, @chapter), class: "btn btn-success pull-right" %>
<h1>
  <%= @chapter.title %>
  <small><%= @book.title %></small>
</h1>
<table class="table table-striped table-hover">
  <% @chapter.sections.each do |section| %>
  <tr>
    <td>
      <%= link_to section.title, book_chapter_section_path(@book, @chapter, section) %>
    </td>
  </tr>
  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AuthoringRaw</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <script src="https://code.jquery.com/jquery-2.2.3.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Author", root_path, class: "navbar-brand" %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li><a href="#">Link</a></li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
  <div class="container">
    <% if flash[:notice] %>
      <div class="alert alert-success alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= flash[:notice] %>
      </div>
    <% end %>
    <% if flash[:error] %>
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= flash[:error] %>
      </div>
    <% end %>
    <%= yield %>
  </div>

</body>
</html>

app/views/sections/_form.html.erb
<%= simple_form_for [@book, @chapter, @section] do |f| %>
  <%= f.input :title %>
  <%= f.input :content %>
  <%= f.submit "#{@section.new_record? ? 'Add' : 'Update'} Section", class: "btn btn-primary btn-lg" %>
<% end %>

app/views/sections/edit.html.erb
<h1>Edit <%= @section.title %></h1>
<h2><small>
  <%= @book.title %> &gt; <%= @chapter.title %>
</small></h2>

<%= render 'sections/form' %>

app/views/sections/new.html.erb
<h1>
  Add new section to
  <%= @chapter.title %>
  <small><%= @book.title %></small>
</h1>

<%= render 'sections/form' %>

app/views/sections/show.html.erb
<%= link_to "Delete", book_chapter_section_path(@book, @chapter, @section), method: :delete, class: "btn btn-danger pull-right", data: {confirm: "Are you sure you want to delete the section?"} %>
<%= link_to "Edit", edit_book_chapter_section_path(@book, @chapter, @section), class: "btn btn-primary pull-right" %>

<h1><%= @section.title %></h1>
<h2><small>
  <%= @book.title %> &gt; <%= @chapter.title %>
</small></h2>